#!/usr/bin/env Rscript
################################################################################
# Deprecated: this historical replay script hard-codes one completed curation
# pass. Durable source-check decisions now live in
# pathogen_association_data/manual/role_annotation/source_check/curated_source_check_decisions.csv
# and are merged by 6_7_Build_Source_Check_Decision_Ledger.R.
################################################################################

suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
  library(tibble)
})

source(file.path("scripts", "associations", "working_inputs.R"))

source_check_dir <- role_source_check_dir

decision_path <- file.path(source_check_dir, "candidate_source_check_decisions.csv")
decision_summary_path <- file.path(source_check_dir, "source_check_decision_summary.csv")
progress_path <- file.path(source_check_dir, "SOURCE_CHECK_PROGRESS.md")

decisions <- tribble(
  ~candidate_row_id, ~source_check_method, ~evidence_found, ~checked_evidence_span, ~checked_evidence_location, ~decision, ~accepted_role, ~accepted_confidence, ~accepted_evidence_scope, ~caveat, ~official_csv_target, ~decision_reason, ~import_ready,
  "candidate_001", "local_pdf_text", "yes", "NM report identifies Oropsylla montana as the most important plague vector for humans in New Mexico; USGS plague circular corroborates flea-borne vector context.", "ZDP-PLG-InvestigationManual.txt lines 24-30; C1372_Plague.txt", "accept", "primary_vector", "high", "regional_public_health", "New Mexico / North America public-health context; not a universal global primary vector claim.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct named-vector support for O. montana with geographic caveat.", TRUE,
  "candidate_002", "local_pdf_text", "yes", "CDC WNV guideline lists Culex quinquefasciatus as a primary WNV vector in southern states and among the three major WNV vectors.", "WestNileVirus-SurveillanceControlGuidelines_508-h.txt lines 105-108, 152-163, 379-380", "accept", "main_vector", "high", "regional_primary_vector", "United States regional vector framing.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct official guideline support.", TRUE,
  "candidate_003", "local_pdf_text", "yes", "CDC WNV guideline lists Culex tarsalis as a primary WNV vector in western states and among the three major WNV vectors.", "WestNileVirus-SurveillanceControlGuidelines_508-h.txt lines 105-108, 152-163, 379-380", "accept", "main_vector", "high", "regional_primary_vector", "United States regional vector framing.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct official guideline support.", TRUE,
  "candidate_004", "local_pdf_text", "yes", "Abreu et al. identify Haemagogus janthinomys and Hg. leucocelaenus as primary vectors in the Brazil 2016-2018 yellow fever outbreak based on distribution, abundance, and natural infection rates.", "Haemagogus...Brazil 2016 2018.txt lines 109-119", "accept", "sylvatic_vector", "high", "outbreak_species_vector", "Brazil Atlantic Forest outbreak context; supports sylvatic/outbreak vector role.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct species-level natural infection and outbreak-vector support.", TRUE,
  "candidate_005", "local_pdf_text", "yes", "Abreu et al. identify Haemagogus leucocelaenus and Hg. janthinomys as primary vectors in the Brazil 2016-2018 yellow fever outbreak based on distribution, abundance, and natural infection rates.", "Haemagogus...Brazil 2016 2018.txt lines 109-119", "accept", "sylvatic_vector", "high", "outbreak_species_vector", "Brazil Atlantic Forest outbreak context; supports sylvatic/outbreak vector role.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct species-level natural infection and outbreak-vector support.", TRUE,
  "candidate_006", "local_pdf_text", "yes", "RVF review states cattle, sheep, goats, and camels are susceptible and serve as amplifying hosts; later section calls cattle, sheep, and goats the most important amplifying hosts.", "linthicum2016.txt lines 58-60, 600-601", "accept", "amplifying_host", "high", "livestock_amplification", "Species-level row derived from livestock statement; goat-specific support is explicit but not a controlled species-only study.", "host_role_evidence.csv; host_role_assignments.csv", "Direct review support for goat as part of named amplifying livestock set.", TRUE,
  "candidate_007", "local_pdf_text", "yes", "RVF review states cattle, sheep, goats, and camels are susceptible and serve as amplifying hosts; later section calls cattle, sheep, and goats the most important amplifying hosts.", "linthicum2016.txt lines 58-60, 600-601", "accept", "amplifying_host", "high", "livestock_amplification", "Species-level row derived from livestock statement; sheep-specific support is explicit and strongest among livestock.", "host_role_evidence.csv; host_role_assignments.csv", "Direct review support for sheep as part of named amplifying livestock set.", TRUE,
  "candidate_008", "official_web", "yes", "ECDC states Hyalomma ticks, mainly H. marginatum, H. anatolicum, H. rufipes and H. asiaticum, are competent CCHFV vectors/reservoirs, with H. marginatum principal in Europe.", "ECDC CCHF factsheet lines 138-140", "accept", "main_vector", "high", "official_species_vector", "Europe-heavy official source; H. marginatum is explicitly principal in Europe.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct official species-level support.", TRUE,
  "candidate_009", "official_web", "yes", "WHO/CDC support wildlife-to-human spillover followed by human-to-human Ebola transmission via body fluids.", "WHO Ebola fact sheet lines 287-289; CDC Ebola spread page lines 117-124", "accept_evidence_only", "amplifying_host", "high", "human_outbreak_transmission", "The candidate role spillover_host is not ideal for Homo sapiens; evidence supports human outbreak amplification after spillover.", "host_role_evidence.csv", "Keep as evidence for human amplification, not as an exact spillover_host import.", FALSE,
  "candidate_010", "official_web", "yes", "WHO states Marburg is transmitted from fruit bats to people and then spreads through human-to-human transmission; CDC similarly describes spillover from bats followed by person-to-person spread.", "WHO Marburg fact sheet lines 219, 230-233; CDC Marburg about lines 140-147", "accept_evidence_only", "amplifying_host", "high", "human_outbreak_transmission", "The candidate role spillover_host is not ideal for Homo sapiens; evidence supports human outbreak amplification after spillover.", "host_role_evidence.csv", "Keep as evidence for human amplification, not as an exact spillover_host import.", FALSE,
  "candidate_011", "official_web", "yes", "WHO Nipah guidance documents animal-to-human risk and measures to reduce human-to-human transmission.", "WHO Nipah fact sheet lines 267-275", "accept_evidence_only", "amplifying_host", "medium", "human_outbreak_transmission", "The candidate role spillover_host is not ideal for Homo sapiens; human-to-human transmission is context-dependent.", "host_role_evidence.csv", "Useful evidence, but role should be reframed as human outbreak amplification if imported.", FALSE,
  "candidate_012", "local_pdf_text", "yes", "Chua et al. isolated Nipah virus from Pteropus hypomelanus urine/fruit swab material and state this corroborates the species as one of the natural hosts.", "1-s2.0-S1286457901015222-main.txt lines 24-32, 68-76, 166-167", "accept", "reservoir_host", "high", "species_natural_host", "Malaysia/Island flying-fox context.", "host_role_evidence.csv; host_role_assignments.csv", "Direct live-virus isolation from species-level bat source.", TRUE,
  "candidate_013", "local_pdf_text", "yes", "Pteropus vampyrus evidence includes isolation/characterization from naturally infected bats and serological/recrudescence evidence in captive P. vampyrus.", "09-1790_finalD.txt lines 28-32, 50-54; evidence-for-nipah-virus-recrudescence...txt lines 449-462, 511-513", "accept", "reservoir_host", "high", "species_natural_host", "Malaysia P. vampyrus context.", "host_role_evidence.csv; host_role_assignments.csv", "Direct species-level natural infection support.", TRUE,
  "candidate_014", "official_web", "yes", "WHO states Lassa is primarily transmitted from Mastomys-contaminated materials and that person-to-person transmission can occur, especially in healthcare settings.", "WHO Lassa fact sheet lines 222-237", "accept_evidence_only", "amplifying_host", "medium", "human_healthcare_transmission", "The candidate role spillover_host is not ideal for Homo sapiens; evidence supports context-dependent person-to-person transmission.", "host_role_evidence.csv", "Useful evidence, but import should use amplification/secondary transmission wording if at all.", FALSE,
  "candidate_015", "local_pdf_text", "yes", "Diallo et al. review supports Aedes furcifer among African dengue vectors and sylvatic-cycle context.", "PIIS2405844022007472.txt", "accept", "sylvatic_vector", "medium", "review_synthesis", "Review-based African sylvatic vector row; not a global urban vector claim.", "vector_role_evidence.csv; vector_role_assignments.csv", "Source-backed candidate row with regional caveat.", TRUE,
  "candidate_016", "secondary_local_plus_missing_primary", "partial", "Candidate primary dengue paper was not locally fetched; CHIKV Yap paper cites Ae. hensilli implication as dengue epidemic vector on Yap/Palau and notes weaker dengue support than CHIKV/Zika.", "tpmd-article-p429.txt lines 336-349, 473-479", "defer", "", "", "missing_primary_source", "Need the Savage 1998 dengue paper text before import; current local evidence is secondary and says dengue support is weaker.", "", "Do not import until primary dengue source is checked.", FALSE,
  "candidate_017", "local_pdf_text", "yes", "Diallo et al. review supports Aedes luteocephalus among African dengue vectors and sylvatic-cycle context.", "PIIS2405844022007472.txt", "accept", "sylvatic_vector", "medium", "review_synthesis", "Review-based African sylvatic vector row; not a global urban vector claim.", "vector_role_evidence.csv; vector_role_assignments.csv", "Source-backed candidate row with regional caveat.", TRUE,
  "candidate_018", "local_pdf_text", "yes", "Rosen demonstrates Aedes polynesiensis can transmit dengue experimentally and discusses epidemiologic observations suggesting it as a natural/important vector in Polynesia.", "tpmd-article-p878.txt lines 18-26, 134-155, 175-176", "accept", "epidemic_vector", "medium", "experimental_and_regional_epidemiology", "Old but direct experimental/epidemiological evidence; Polynesia context.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct species-level support.", TRUE,
  "candidate_019", "local_pdf_text", "yes", "Diallo et al. review supports Aedes taylori among African dengue vectors and sylvatic-cycle context.", "PIIS2405844022007472.txt", "accept", "sylvatic_vector", "medium", "review_synthesis", "Review-based African sylvatic vector row; not a global urban vector claim.", "vector_role_evidence.csv; vector_role_assignments.csv", "Source-backed candidate row with regional caveat.", TRUE,
  "candidate_020", "local_pdf_text", "yes", "Seery et al. describe black-tailed prairie dogs as major amplifying hosts for Yersinia pestis and document high mortality epizootic context.", "jmedent40-0718.txt lines 18-24, 43-49", "accept", "amplifying_host", "medium", "regional_epizootic_host", "North American prairie-dog epizootic role; not a universal plague reservoir claim.", "host_role_evidence.csv; host_role_assignments.csv", "Direct species-level amplifying-host wording.", TRUE,
  "candidate_021", "local_pdf_text", "yes", "Miarinjara et al. and supporting literature describe Oropsylla hirsuta as an abundant prairie dog flea vector and support its role in prairie dog plague epizootics.", "tjac021.txt lines 33-42, 392-395; C1372_Plague.txt lines 4261-4272", "accept", "candidate_vector", "medium", "regional_epizootic_vector", "Prairie-dog epizootic context; keep candidate rather than main/primary.", "vector_role_evidence.csv; vector_role_assignments.csv", "Good species-level candidate vector support.", TRUE,
  "candidate_022", "local_pdf_text", "yes", "CDC WNV guideline names American robin/Turdus migratorius as an amplifier host example in many locations.", "WestNileVirus-SurveillanceControlGuidelines_508-h.txt lines 132-134", "accept", "amplifying_host", "medium", "regional_amplifier_host", "Species name in guideline has OCR typo; map to Turdus migratorius with review note.", "host_role_evidence.csv; host_role_assignments.csv", "Official named-host amplifier evidence.", TRUE,
  "candidate_023", "local_pdf_text", "yes", "CDC WNV guideline describes Culex salinarius as an important enzootic and epidemic vector in the northeastern United States.", "WestNileVirus-SurveillanceControlGuidelines_508-h.txt lines 111-116", "accept", "epidemic_vector", "medium", "regional_vector", "Northeastern United States context; not a primary vector nationally.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct official regional vector support.", TRUE,
  "candidate_024", "local_pdf_text", "yes", "Yap CHIKV study detected multiple positive Ae. hensilli pools, argues Ae. hensilli was more important than Ae. aegypti on Yap, and explicitly incriminates it as an epidemic vector.", "tpmd-article-p429.txt lines 312-349, 379-381", "accept", "epidemic_vector", "medium", "outbreak_species_vector", "Yap outbreak context; not a global CHIKV vector claim.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct species-level outbreak/vector evidence.", TRUE,
  "candidate_025", "local_pdf_text", "yes", "RVF review states cattle, sheep, and goats are the most important amplifying hosts; cattle are also susceptible and important in regional livestock-density risk.", "linthicum2016.txt lines 58-60, 600-601, 858-859", "accept", "amplifying_host", "medium", "livestock_amplification", "Cattle are important amplifying livestock but generally less susceptible to clinical disease than sheep/goats.", "host_role_evidence.csv; host_role_assignments.csv", "Direct review support for cattle as part of named amplifying livestock set.", TRUE,
  "candidate_026", "local_pdf_text", "yes", "RVF sources identify Aedes mcintoshi among primary floodwater Aedes vectors and describe infected Aedes eggs/maintenance-cycle ecology.", "linthicum2016.txt lines 228-229, 384-393, 517-523; Rift-Valley-fever...txt lines 90-92", "accept", "enzootic_maintenance_vector", "medium", "review_synthesis", "Review-based species row; maintenance wording is ecological synthesis.", "vector_role_evidence.csv; vector_role_assignments.csv", "Good source-backed maintenance-vector support.", TRUE,
  "candidate_027", "local_pdf_text", "yes", "RVF sources list Culex poicilipes among RVFV vectors and describe Culex secondary vectors transmitting from highly viraemic animals to humans.", "linthicum2016.txt lines 293-295; Rift-Valley-fever...txt lines 100-107", "accept", "epidemic_vector", "medium", "secondary_epidemic_vector", "Best interpreted as secondary/epidemic vector rather than maintenance vector.", "vector_role_evidence.csv; vector_role_assignments.csv", "Source-backed regional epidemic vector support.", TRUE,
  "candidate_028", "local_pdf_text", "yes", "Ortiz/Weaver study reports high susceptibility and transmission potential of Psorophora confinnis and concludes it is an important bridge vector for enzootic and epizootic VEEV.", "ortiz2005.txt lines 14-31, 391-418", "accept", "bridge_vector", "medium", "experimental_vector_competence", "Northern South America / VEEV subtype context; bridge-vector role is supported but regional.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct species-level competence and bridge-vector support.", TRUE,
  "candidate_029", "official_web", "yes", "ECDC states Hyalomma ticks, mainly H. marginatum, H. anatolicum, H. rufipes and H. asiaticum, are competent CCHFV vectors/reservoirs.", "ECDC CCHF factsheet lines 138-140", "accept", "main_vector", "medium", "official_species_vector", "Species is named as competent vector/reservoir; main-vector strength is less Europe-specific than H. marginatum.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct official species-level support.", TRUE,
  "candidate_030", "official_web", "yes", "ECDC states CCHFV was detected in H. lusitanicum in Spain before the first human case and that this species seems important in virus circulation there.", "ECDC CCHF factsheet lines 138-140", "accept", "enzootic_maintenance_vector", "medium", "regional_virus_circulation", "Spain-specific circulation role; do not generalize globally.", "vector_role_evidence.csv; vector_role_assignments.csv", "Official regional support for virus-circulation role.", TRUE,
  "candidate_031", "official_web", "yes", "ECDC states Hyalomma ticks, mainly H. marginatum, H. anatolicum, H. rufipes and H. asiaticum, are competent CCHFV vectors/reservoirs.", "ECDC CCHF factsheet lines 138-140", "accept", "main_vector", "medium", "official_species_vector", "Species is named as competent vector/reservoir; regional importance varies.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct official species-level support.", TRUE,
  "candidate_032", "local_pdf_text", "yes", "Systematic review finds Culicoides sonorensis and C. paraensis consistently demonstrate high competence to transmit OROV, but emphasizes current outbreak vectors remain uncertain.", "journal.pntd.0013014.txt lines 15-29, 199-212, 277-287", "accept", "competent_vector_only", "medium", "experimental_competence_only", "Competence evidence only; no evidence that C. sonorensis is a field vector in current outbreaks.", "vector_role_evidence.csv; vector_role_assignments.csv", "Strong competence-only support.", TRUE,
  "candidate_033", "local_pdf_text", "yes", "Zhao et al. report E. amurensis hedgehogs with high SFTSV seroprevalence/RNA prevalence, robust viremias, completed tick-host cycle, and conclude hedgehogs are notable wildlife amplifying hosts.", "22-0668.txt lines 13-34, 80-87, 165-174", "accept", "amplifying_host", "medium", "regional_wildlife_amplifier", "China/endemic-area hedgehog evidence; not a global host claim.", "host_role_evidence.csv; host_role_assignments.csv", "Direct species-level amplifying-host support.", TRUE,
  "candidate_034", "local_pdf_text", "yes", "Fang et al. demonstrate H. flava can acquire SFTSV and transmit it through stages and to rabbits; they conclude H. flava is a competent vector/reservoir.", "1-s2.0-S1877959X22002023-main.txt lines 240-263, 351-356", "accept", "competent_vector_only", "medium", "experimental_competence", "Competence/experimental transmission support; field importance remains context-dependent.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct experimental competence support.", TRUE,
  "candidate_035", "local_pdf_text", "yes", "Hu et al. show I. sinensis transovarial transmission, adult tick-to-mouse transmission, and conclude it can play roles in maintaining/transmitting SFTSV.", "document.txt lines 24-36, 72-77, 379-383, 503-514", "accept", "candidate_vector", "medium", "experimental_candidate_vector", "Evidence is experimental and geographically bounded; keep candidate rather than main vector.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct experimental candidate-vector support.", TRUE,
  "candidate_036", "local_pdf_text", "yes", "TBEV reservoir-host review and mouse infection paper support Apodemus flavicollis as a species-level small-rodent host in the TBEV transmission cycle.", "viruses-11-00669.txt; s41598-023-47697-2.txt", "accept", "reservoir_host", "medium", "review_plus_experimental_host", "Review plus experimental support; reservoir role is shared with broader small rodent community.", "host_role_evidence.csv; host_role_assignments.csv", "Species-level TBEV host support is sufficient for candidate import.", TRUE,
  "candidate_037", "local_pdf_text", "yes", "TBEV reservoir-host review supports Myodes glareolus/bank vole as a species-level small-rodent reservoir host.", "viruses-11-00669.txt", "accept", "reservoir_host", "medium", "review_synthesis", "Review-based support; reservoir role is shared with broader small rodent community.", "host_role_evidence.csv; host_role_assignments.csv", "Species-level TBEV host support is sufficient for candidate import.", TRUE,
  "candidate_038", "local_pdf_text", "yes", "Dermacentor reticulatus study demonstrates infected ticks transmit TBEV to mice and concludes D. reticulatus is a biologically effective, underrecognized TBEV vector.", "1-s2.0-S1877959X19305138-main.txt lines 34-54, 174-192, 211-218", "accept", "candidate_vector", "medium", "experimental_candidate_vector", "Non-core/underrecognized vector; do not upgrade to main vector.", "vector_role_evidence.csv; vector_role_assignments.csv", "Direct experimental vector support.", TRUE,
  "candidate_039", "local_pdf_text", "yes", "TBEV review states Haemaphysalis concinna is one of the major vectors for TBEV transmission in Asia.", "microbiolres-15-00174.txt lines 409-413", "accept", "candidate_vector", "medium", "review_synthesis", "Review-based regional Asia vector row; candidate status is safer than main vector.", "vector_role_evidence.csv; vector_role_assignments.csv", "Source-backed non-core candidate vector support.", TRUE,
  "candidate_040", "local_pdf_text", "yes", "Walsh et al. describe Ebola Zaire introductions into humans when people handled infected gorilla/chimpanzee carcasses during ape die-offs.", "document_ebola1.txt lines 8-20, 30-36", "accept", "spillover_host", "medium", "wildlife_source_host", "Great apes are spillover/source animals in documented chains, not reservoir hosts.", "host_role_evidence.csv; host_role_assignments.csv", "Direct wildlife source/species evidence with non-reservoir caveat.", TRUE,
  "candidate_041", "local_pdf_text", "yes", "Walsh et al. describe Ebola Zaire introductions into humans when people handled infected gorilla/chimpanzee carcasses during ape die-offs.", "document_ebola1.txt lines 8-20, 30-36", "accept", "spillover_host", "medium", "wildlife_source_host", "Great apes are spillover/source animals in documented chains, not reservoir hosts.", "host_role_evidence.csv; host_role_assignments.csv", "Direct wildlife source/species evidence with non-reservoir caveat.", TRUE,
  "candidate_042", "official_web", "yes", "WHO Marburg fact sheet states first recognized outbreaks were associated with laboratory work using African green monkeys imported from Uganda.", "WHO Marburg fact sheet lines 224-226, 259-264", "accept", "incidental_host", "medium", "historical_source_animal", "Historical/laboratory-associated source-animal role; not reservoir evidence.", "host_role_evidence.csv; host_role_assignments.csv", "Official historical source-animal support.", TRUE,
  "candidate_043", "local_pdf_text", "yes", "Pteropus lylei sources report Nipah virus in Lyle's flying foxes and molecular characterization from Thai fruit bats.", "19-1284.txt; 10.5372_1905-7415.0706.244.txt lines 18-20, 256-258", "accept", "reservoir_host", "medium", "regional_species_natural_host", "Cambodia/Thailand species-level support; add alongside existing Pteropus spp. group with caveat.", "host_role_evidence.csv; host_role_assignments.csv", "Reasonable species-level reservoir support.", TRUE,
  "candidate_044", "local_pdf_text", "yes", "Kerala sources report Nipah sequences/detection in Pteropus medius during human outbreaks.", "18-1076-1.txt; 12879_2021_Article_5865.txt", "accept", "reservoir_host", "medium", "regional_species_natural_host", "India/Kerala species-level evidence; add alongside existing Pteropus spp. group with caveat.", "host_role_evidence.csv; host_role_assignments.csv", "Reasonable species-level reservoir support.", TRUE,
  "candidate_045", "official_web", "yes", "WHO 2025 Sudan virus DON documents confirmed human cases, contact-linked secondary cases, and ongoing investigation of the outbreak source.", "WHO DON 2025-DON556 lines 217-239, 242-244", "accept_evidence_only", "amplifying_host", "medium", "human_outbreak_transmission", "The animal source is unresolved; Homo sapiens evidence supports outbreak transmission rather than spillover_host as a role.", "host_role_evidence.csv", "Useful human outbreak evidence but exact candidate role should be reframed.", FALSE,
  "candidate_046", "local_pdf_plus_official_web", "partial", "Primary field study strongly identifies C. musculinus as principal Junin reservoir and detects C. laucha rarely; Canada sheet lists C. laucha among natural hosts and principal reservoirs.", "Mills-Caldern-JuninVirus-LongitudinalStudy-1992.txt lines 21-35, 216-217, 696-698, 828-830; Canada Junin sheet lines 99-123", "accept_evidence_only", "reservoir_host", "low", "secondary_or_minor_reservoir_candidate", "Evidence for C. laucha is weaker than for C. musculinus; treat as possible/minor reservoir candidate, not equal primary reservoir.", "host_role_evidence.csv", "Do not import as medium reservoir_host without manual review; evidence supports only a caveated candidate.", FALSE,
  "candidate_047", "local_pdf_text", "yes", "Olayemi et al. report LASV in Hylomyscus pamfi and conclude H. pamfi and M. erythroleucus are full-fledged reservoirs; later review lists H. pamfi among four LASV reservoir species.", "srep25280.txt lines 13-20, 183-190, 203-207; viruses-12-00312.txt lines 475-478", "accept", "reservoir_host", "medium", "species_reservoir", "Newer/additional reservoir species; region-specific and less canonical than M. natalensis.", "host_role_evidence.csv; host_role_assignments.csv", "Direct species-level reservoir support.", TRUE,
  "candidate_048", "local_pdf_text", "yes", "Olayemi et al. report LASV in Mastomys erythroleucus and conclude H. pamfi and M. erythroleucus are full-fledged reservoirs; later review lists M. erythroleucus among four LASV reservoir species.", "srep25280.txt lines 13-20, 107-118, 183-190, 203-207; viruses-12-00312.txt lines 475-478", "accept", "reservoir_host", "medium", "species_reservoir", "Additional reservoir species; region-specific and less canonical than M. natalensis.", "host_role_evidence.csv; host_role_assignments.csv", "Direct species-level reservoir support.", TRUE,
  "candidate_049", "local_pdf_plus_official_web", "yes", "WHO reports 2024 A(H5N1) outbreaks in US dairy cattle; Nature/mbio sources document HPAI H5N1 in dairy cattle and cattle-to-cattle/milking-related spread.", "WHO influenza fact sheet lines 247-251; s41586-024-07766-6.txt lines 29-37; mostafa-et-al-2024...txt lines 287-295", "accept_evidence_only", "susceptible_host_only", "medium", "recent_outbreak_susceptible_host", "Candidate proposed spillover_host, but current repo convention already uses susceptible_host_only for Bos taurus H5N1; avoid implying reservoir/amplifier without review.", "host_role_evidence.csv", "Evidence is strong for cattle infection/outbreak host, but role should be conservative.", FALSE,
  "candidate_050", "local_pdf_text", "yes", "Cat review states domestic cats and large felids are naturally and experimentally susceptible to HPAI H5N1; infections mostly follow contact with infected birds/raw poultry and cat-to-cat transmission may occur.", "marschall-hartmann-2008...txt lines 11-22, 31-38, 90-118", "accept", "susceptible_host_only", "medium", "susceptible_host", "Susceptible host evidence only; role in broader epidemiology remains uncertain.", "host_role_evidence.csv; host_role_assignments.csv", "Direct susceptible-host support.", TRUE,
  "candidate_051", "local_pdf_text", "yes", "Nature 2025 report and review support MPXV transmission from fire-footed rope squirrels to sooty mangabeys, with mangabeys as affected/spillover primates rather than reservoirs.", "s41586-025-10086-y.txt; ofae503.txt", "accept", "spillover_host", "medium", "single_outbreak_spillover", "Single-chain/specific-event evidence; not reservoir evidence.", "host_role_evidence.csv; host_role_assignments.csv", "Accept as caveated spillover host.", TRUE,
  "candidate_052", "local_pdf_text", "yes", "CDC/NEJM/prairie-dog model sources document 2003 US mpox outbreak in domesticated prairie dogs, human cases from direct contact, and experimental animal-to-animal transmission.", "cdc_132180_DS1.txt lines 29-43; NEJMoa032299.txt lines 44-57, 240-264; mpox_dog.txt lines 395-398, 430-432", "accept", "amplifying_host", "medium", "outbreak_amplifying_host", "Prairie dogs were outbreak amplification/transmission hosts in 2003 US context; not natural reservoir evidence.", "host_role_evidence.csv; host_role_assignments.csv", "Direct outbreak and experimental transmission support.", TRUE,
  "candidate_053", "official_web_plus_secondary_local", "yes", "CDC states Zika is primarily transmitted by Ae. aegypti/albopictus and that Ae. hensilli may contribute in Pacific Islands; Yap CHIKV paper notes Ae. hensilli was implicated as a Zika epidemic vector on Yap and lab studies support Zika vector status.", "CDC Zika transmission page lines 108-130; tpmd-article-p429.txt lines 340-349, 392-393, 478-479", "accept", "candidate_vector", "low", "regional_candidate_vector", "Pacific Islands/Yap evidence; keep low-confidence candidate and do not upgrade to epidemic/main vector without primary Zika paper.", "vector_role_evidence.csv; vector_role_assignments.csv", "Official CDC plus secondary local support justifies low-confidence candidate row.", TRUE
)

original <- read_csv(decision_path, show_col_types = FALSE)

if (!"file_name" %in% names(original)) {
  stop("Expected file_name column is missing from candidate_source_check_decisions.csv")
}

missing_ids <- setdiff(decisions$candidate_row_id, original$candidate_row_id)
if (length(missing_ids) > 0) {
  stop("Decision rows refer to unknown candidate_row_id values: ", paste(missing_ids, collapse = ", "))
}

if (anyDuplicated(decisions$candidate_row_id)) {
  dupes <- unique(decisions$candidate_row_id[duplicated(decisions$candidate_row_id)])
  stop("Duplicate decision rows for: ", paste(dupes, collapse = ", "))
}

filled <- original %>%
  left_join(decisions, by = "candidate_row_id", suffix = c("", ".curated")) %>%
  mutate(
    source_checked = if_else(!is.na(decision.curated), "yes", source_checked),
    source_check_method = coalesce(source_check_method.curated, source_check_method),
    evidence_found = coalesce(evidence_found.curated, evidence_found),
    checked_evidence_span = coalesce(checked_evidence_span.curated, checked_evidence_span),
    checked_evidence_location = coalesce(checked_evidence_location.curated, checked_evidence_location),
    decision = coalesce(decision.curated, decision),
    accepted_role = coalesce(accepted_role.curated, accepted_role),
    accepted_confidence = coalesce(accepted_confidence.curated, accepted_confidence),
    accepted_evidence_scope = coalesce(accepted_evidence_scope.curated, accepted_evidence_scope),
    caveat = coalesce(caveat.curated, caveat),
    official_csv_target = coalesce(official_csv_target.curated, official_csv_target),
    decision_reason = coalesce(decision_reason.curated, decision_reason),
    reviewer = if_else(!is.na(decision.curated), "Codex source check", reviewer),
    review_date = if_else(!is.na(decision.curated), as.character(Sys.Date()), as.character(review_date)),
    import_ready = coalesce(as.character(import_ready.curated), as.character(import_ready))
  ) %>%
  select(-ends_with(".curated"))

write_csv(filled, decision_path, na = "")

summary <- filled %>%
  count(decision, import_ready, name = "n") %>%
  arrange(decision, import_ready)

source_summary <- filled %>%
  count(source_check_method, decision, name = "n") %>%
  arrange(source_check_method, decision)

write_csv(summary, decision_summary_path, na = "")

progress <- c(
  "# Source Check Progress",
  "",
  paste0("Generated: ", Sys.time()),
  "",
  "## Scope",
  "",
  paste0("- Candidate rows checked: ", nrow(filled)),
  paste0("- Source-checked rows: ", sum(filled$source_checked == "yes", na.rm = TRUE)),
  paste0("- Import-ready rows: ", sum(filled$import_ready == "TRUE", na.rm = TRUE)),
  "- Official role CSVs were not modified by this script.",
  "- The user-added `file_name` column is preserved.",
  "",
  "## Decision Summary",
  "",
  paste(capture.output(print(summary, n = Inf)), collapse = "\n"),
  "",
  "## Method Summary",
  "",
  paste(capture.output(print(source_summary, n = Inf)), collapse = "\n"),
  "",
  "## Main Caveats",
  "",
  "- Human rows proposed as `spillover_host` were generally kept as evidence-only because the sources support human outbreak amplification/secondary transmission more cleanly than a spillover-host role.",
  "- `Bos taurus` for H5N1 was kept evidence-only with `susceptible_host_only` because infection/outbreak evidence is strong, but reservoir/amplifier implications need review.",
  "- `Calomys laucha` for Junin virus was kept evidence-only because sources support possible/minor reservoir status, while the strongest field evidence still favors `Calomys musculinus`.",
  "- `Aedes hensilli` for dengue was deferred because the primary dengue source was not locally available; current support is secondary.",
  "- No assignment/evidence rows were imported into official role CSVs yet."
)

writeLines(progress, progress_path)

cat("Wrote source-check decisions:", decision_path, "\n")
cat("Wrote decision summary:", decision_summary_path, "\n")
cat("Wrote progress note:", progress_path, "\n")
print(summary, n = Inf)
